name: Release

on:
  release:
    types: [released]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 17
      - name: Update version property
        uses: Reedyuk/write-properties@v1.0.3
        with:
          path: 'library/gradle.properties'
          property: 'MODULE_VERSION_NUMBER'
          value: ${{ github.ref_name }}
      - name: Setup cocoapods
        run: gem install cocoapods-generate
      - name: Static Analysis
        run: ./gradlew detekt
      - name: Verify Tests Coverage
        run: ./gradlew koverVerify
      - name: Build
        run: ./gradlew build
      - name: Run publish
        run: ./gradlew publish
        env:
          sonatypeUsernameEnv: ${{ secrets.SONATYPEUSERNAME }}
          sonatypePasswordEnv: ${{ secrets.SONATYPEPASSWORD }}
          ORG_GRADLE_PROJECT_signingKey: ${{ secrets.GPG_KEY }}
          ORG_GRADLE_PROJECT_signingPassword: ${{ secrets.GPG_KEY_PASS }}
